### ISSUE TITLE
Not always working

### ISSUE THREAD

**Issue by tiramon** [Azkellas/cgenhancer#1]
I use chrome with tampermonkey and quite often i see in the console that CGEnhancer is working, but there are no ranks in 'Last Battles'. Often i have to refresh a few times to get the ranks.

**Comment by Azkellas** [comment]
Hi,
Yes I saw this issue as well, though one refresh was enough.
If you have enough battles in the tab, scrolling down then up is enough. At worst, closing the last battles tab and opening it again do the job.

It seems that it happens when the tab was not opened for some time (>1mn). The leaderboard is refreshed at the same time the ranks are displayed, so the data is empty.
I updated a fix, please tell me if it still doesn't work.
